port: "8080"
db:
    host: localhost
    port: "3306"
    name: rmx-dev-test
    user: rmx
    password: postgrespw
auth:
    enable: true
    google:
        client_id: "709647974918-5anv6uh2tiqfe2gba0pm5u0gpnvj65jd.apps.googleusercontent.com"
        client_secret: "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"
dev: true
