version: 3

tasks:
  cache:
    cmds:
      - go get -d ./...

  svelte:
    cmds:
      - cd svelte && bun run build

  dev:
    deps:
      - cache
      - svelte
    cmds: 
      - go run ./cmd/server/

  htmx:
    cmds:
      - curl -L -o static/htmx.min.js https://unpkg.com/htmx.org@latest/dist/htmx.min.js
      - curl -L -o static/hyperscript.min.js https://unpkg.com/hyperscript.org@latest/dist/_hyperscript.min.js