// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type Jam struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Bpm       int32     `json:"bpm"`
	Capacity  int32     `json:"capacity"`
	CreatedAt time.Time `json:"createdAt"`
}
