// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package user

import (
	"database/sql"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	Username  string
	Email     interface{}
	Password  interface{}
	CreatedAt sql.NullTime
}
