// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package user

import (
	"time"
)

type User struct {
	ID        string
	Username  string
	Email     string
	Password  string
	CreatedAt time.Time
}
