// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, is_admin, picture, blocked)
    VALUES ($1, $2, $3, $4, $5)
RETURNING
    id, username, email, is_admin, picture, blocked, last_login, created_at, updated_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	IsAdmin  bool   `json:"isAdmin"`
	Picture  string `json:"picture"`
	Blocked  bool   `json:"blocked"`
}

func (q *Queries) CreateUser(ctx context.Context, arg *CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Username,
		arg.Email,
		arg.IsAdmin,
		arg.Picture,
		arg.Blocked,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsAdmin,
		&i.Picture,
		&i.Blocked,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserByEmail = `-- name: DeleteUserByEmail :exec
DELETE FROM users
WHERE email = $1
`

func (q *Queries) DeleteUserByEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByEmail, email)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUserByID, id)
	return err
}

const deleteUserByUsername = `-- name: DeleteUserByUsername :exec
DELETE FROM users
WHERE username = $1
`

func (q *Queries) DeleteUserByUsername(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, deleteUserByUsername, username)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id, username, email, is_admin, picture, blocked, last_login, created_at, updated_at
FROM
    users
WHERE
    email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsAdmin,
		&i.Picture,
		&i.Blocked,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id, username, email, is_admin, picture, blocked, last_login, created_at, updated_at
FROM
    users
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsAdmin,
		&i.Picture,
		&i.Blocked,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id, username, email, is_admin, picture, blocked, last_login, created_at, updated_at
FROM
    users
WHERE
    username = $1
LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsAdmin,
		&i.Picture,
		&i.Blocked,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id, username, email, is_admin, picture, blocked, last_login, created_at, updated_at
FROM
    users
ORDER BY
    username
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg *ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.IsAdmin,
			&i.Picture,
			&i.Blocked,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserByEmail = `-- name: UpdateUserByEmail :one
UPDATE
    users
SET
    username = $2,
    is_admin = $3,
    picture = $4,
    blocked = $5,
    last_login = $6
WHERE
    email = $1
RETURNING
    id, username, email, is_admin, picture, blocked, last_login, created_at, updated_at
`

type UpdateUserByEmailParams struct {
	Email     string    `json:"email"`
	Username  string    `json:"username"`
	IsAdmin   bool      `json:"isAdmin"`
	Picture   string    `json:"picture"`
	Blocked   bool      `json:"blocked"`
	LastLogin time.Time `json:"lastLogin"`
}

func (q *Queries) UpdateUserByEmail(ctx context.Context, arg *UpdateUserByEmailParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserByEmail,
		arg.Email,
		arg.Username,
		arg.IsAdmin,
		arg.Picture,
		arg.Blocked,
		arg.LastLogin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsAdmin,
		&i.Picture,
		&i.Blocked,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserByID = `-- name: UpdateUserByID :one
UPDATE
    users
SET
    username = $2,
    email = $3,
    is_admin = $4,
    picture = $5,
    blocked = $6,
    last_login = $7
WHERE
    id = $1
RETURNING
    id, username, email, is_admin, picture, blocked, last_login, created_at, updated_at
`

type UpdateUserByIDParams struct {
	ID        uuid.UUID `json:"id"`
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	IsAdmin   bool      `json:"isAdmin"`
	Picture   string    `json:"picture"`
	Blocked   bool      `json:"blocked"`
	LastLogin time.Time `json:"lastLogin"`
}

func (q *Queries) UpdateUserByID(ctx context.Context, arg *UpdateUserByIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserByID,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.IsAdmin,
		arg.Picture,
		arg.Blocked,
		arg.LastLogin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsAdmin,
		&i.Picture,
		&i.Blocked,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserByUsername = `-- name: UpdateUserByUsername :one
UPDATE
    users
SET
    email = $2,
    is_admin = $3,
    picture = $4,
    blocked = $5,
    last_login = $6
WHERE
    username = $1
RETURNING
    id, username, email, is_admin, picture, blocked, last_login, created_at, updated_at
`

type UpdateUserByUsernameParams struct {
	Username  string    `json:"username"`
	Email     string    `json:"email"`
	IsAdmin   bool      `json:"isAdmin"`
	Picture   string    `json:"picture"`
	Blocked   bool      `json:"blocked"`
	LastLogin time.Time `json:"lastLogin"`
}

func (q *Queries) UpdateUserByUsername(ctx context.Context, arg *UpdateUserByUsernameParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserByUsername,
		arg.Username,
		arg.Email,
		arg.IsAdmin,
		arg.Picture,
		arg.Blocked,
		arg.LastLogin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.IsAdmin,
		&i.Picture,
		&i.Blocked,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
