// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID   `json:"id"`
	Username  string      `json:"username"`
	Email     interface{} `json:"email"`
	CreatedAt time.Time   `json:"createdAt"`
}
